### ISSUE TITLE
Problema con la utilización del paquete por parte de un usuario cualquiera

### ISSUE THREAD

**Issue by alu0100406122** [ULL-ESIT-SYTW-1617/creacion-de-paquetes-y-modulos-en-nodejs-josue-nayra#1]
Problema con la utilización del paquete por parte de un usuario, a la hora de ejecutar el comando en si, no se crea el directorio correspondiente con la estructura del libro.

@JosueTC94

**Comment by JosueTC94** [comment]
Había que añadir algunas devDependencies como dependencies en el package.json para que cuando el usuario instalara el paquete se instalasen también las  librerías necesarias. 
Por otro lado, había que añadir una sección bin del package.json para que fuese posible la ejecución.
